### ISSUE TITLE
encode.emit genericity

### ISSUE THREAD

**Issue by durban** [scodec/scodec-stream#12]
Is there any reason for [encode.emit](https://github.com/scodec/scodec-stream/blob/series/1.0.x/src/main/scala/scodec/stream/encode/package.scala#L38) to return a `StreamEncoder[Nothing]` instead of being generic and returning a `StreamEncoder[A]`? Wouldn't something like this work?
```scala
    def emit[A](bits: BitVector): StreamEncoder[A] = {
      StreamEncoder.instance[A] { h =>
        Pull.output1(bits) >> Pull.pure(h -> encode.empty[A])
      }
    }
```

**Comment by durban** [comment]
Well, I'm using this, and it seems to work fine so far. I can send a pull request if you think it's useful.

**Comment by mpilquist** [comment]
Hey sorry, I missed this when you first opened it. Given that `StreamEncoder` is invariant in `A`, then yeah, `emit` should be polymorphic in `A`. PR would be great.
