### ISSUE TITLE
Incorrect behavior in StreamDecoder with listOfN codec

### ISSUE THREAD

**Issue by dylemma** [scodec/scodec-stream#58]
Hello. First off, sorry if this is the wrong place to report the issue, I think the problem originates from the `listOfN` implementation in Scodec, but it manifests itself when using `StreamDecoder` with a codec using `listOfN`. Please let me know if you'd like me to re-open the issue in the Scodec main repo.

If you have some encoded list of N items, but the end of item M < N happens to align with the end of the current decoding buffer (0 bits remaining), the decoder will report a list of `M` items, then error out because it was expecting `N`.

I was able to distill this down to a small example:

```scala
object Test extends IOApp {
	def run(args: List[String]): IO[ExitCode] = {
		val in = List(1,2,3,4,5,6,7)
		val codec = listOfN(uint16, uint16)
		val encodedBytes = codec.encode(in).require.toByteArray
		println(encodedBytes.toList)

		val firstPart = encodedBytes.slice(0, 6)
		val secondPart = encodedBytes.slice(6, encodedBytes.length)
		// val stream = Stream.chunk[IO, Byte](Chunk.array(encodedBytes)) // WORKS
		val stream = Stream.chunk[IO, Byte](Chunk.array(firstPart)) ++ Stream.chunk[IO, Byte](Chunk.array(secondPart)) // ERROR

		val pipe = StreamDecoder.many(codec).toPipeByte[IO]

		stream.through(pipe).evalTap{ list => IO(println(s"Decoded: $list")) }.compile.drain >> IO(ExitCode.Success)
	}
}
```

dependencies:
```scala
// a few of these not strictly necessary for the example above, 
// but I was playing with a bit more and it's easier to leave them all in for now
libraryDependencies ++= Seq(
  "org.scodec" %% "scodec-core" % "1.11.7",
  "org.scodec" %% "scodec-stream" % "2.0.0",
  "co.fs2" %% "fs2-core" % "2.2.1",
  "co.fs2" %% "fs2-io" % "2.2.1",
  "co.fs2" %% "fs2-reactive-streams" % "2.2.1",
  "org.typelevel" %% "cats-core" % "2.0.0",
  "org.typelevel" %% "cats-kernel" % "2.0.0",
  "org.typelevel" %% "cats-effect" % "2.0.0"
)
```

In the example, I split the encoded array into two chunks, where the first chunk is just enough to hold the list length plus two of the list items. The output is as follows:

```
[info] running Test
List(0, 7, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7)
scodec.stream.CodecError: Insufficient number of elements: decoded 2 but should have decoded 7
[error] Nonzero exit code: 1
```

If you use the commented-out `val stream` which uses the whole array in one chunk, the list is successfully decoded.

My current use-case is to receive a stream of data in an Http4s webserver, and as far as I'm aware, I don't have any control over where the byte/buffer boundaries end up. Every once in a while the request/response handler will crash with the error above, apparently due to the way the items in the stream happen to line up.

I think the underlying issue is the way the `ListCodec` is used under the hood - if you have a `listOfN`, the `N` is passed as a `limit` to `Decoder.decodeCollect[List, A](codec, limit)(buffer)` and so you can end up with fewer items than intended as long as there are no more bits after the last `A` in the buffer. I *think* a solution could be to make `listOfN` return an `Err.InsufficientBits` instead of a plain `Err("...")` so that the `StreamDecoder` will continue its loop instead of crashing, but maybe you can think of a better way.

**Comment by dylemma** [comment]
I think this is fixed on the `develop` branch since my PR was merged. Could we get a release of that? I'm eagerly awaiting a version of this project that works with the 3.0 versions of fs2 and cats-effect on scala 2.12/2.13. If there are any outstanding tasks holding up the release, I could probably contribute a PR to help out.

**Comment by mpilquist** [comment]
3.0.0 is out but without your fix. https://search.maven.org/artifact/org.scodec/scodec-stream_3/3.0.0/jar

I just pushed a 3.0.1 tag to pull in the updated scodec-core dependency version, though you could always pull in 1.11.8 manually in your project.

**Comment by dylemma** [comment]
Oh awesome! I guess I missed the memo on that release (probably thought it wasn't done because `develop` wasn't merged). I'll go ahead and close this issue then.

**Comment by mpilquist** [comment]
:+1: I really need to work on docs and announcements and the site and stuff but I'm swamped with other stuff. Just keeping up with releases has been most of my OSS time (and eating in to some non-OSS time too).
