### ISSUE TITLE
release 0.12.a with scalaz-stream-0.8a

### ISSUE THREAD

**Issue by gabor-aranyossy** [scodec/scodec-stream#9]
Could you please create a release with **scalaz-stream 0.8a** as dependency so it brings **scalaz 7.2.0** as transitive?

**Comment by mpilquist** [comment]
@gabor-aranyossy Sure, I'll publish one later today and update this ticket when it is out.

**Comment by mpilquist** [comment]
Published for 2.10 and 2.11 with version number 0.12.0-a.

**Comment by gabor-aranyossy** [comment]
@mpilquist Thanks for the quick release. 👍
